/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import controllers.GeneroController;
import java.awt.PopupMenu;
import java.util.List;
import javax.swing.JOptionPane;
import models.Genero;

/**
 *
 * @author Machichu
 */
public class AltaGenero extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaGenero
     */
    public AltaGenero() {
        initComponents();
        GeneroController GenController = new GeneroController();
        VentanaError.setVisible(false);
        
        List<String> nombresGenero = GenController.obtenerNombresGeneros();
            for (String nombreG : nombresGenero) {
                GeneroPadreBox.addItem(nombreG);
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        AceptarBtn = new javax.swing.JButton();
        CancelarBtn = new javax.swing.JButton();
        VentanaError = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AceptarErrorBtn = new javax.swing.JButton();
        GeneroPadreBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textoIngresado = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta de Genero");
        setMinimumSize(new java.awt.Dimension(350, 300));
        setPreferredSize(new java.awt.Dimension(325, 360));

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 140));

        AceptarBtn.setText("Aceptar");
        AceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBtnActionPerformed(evt);
            }
        });

        CancelarBtn.setText("Cancelar");
        CancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("ERROR: El genero ingresado ya existe");

        AceptarErrorBtn.setText("OK");
        AceptarErrorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarErrorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VentanaErrorLayout = new javax.swing.GroupLayout(VentanaError);
        VentanaError.setLayout(VentanaErrorLayout);
        VentanaErrorLayout.setHorizontalGroup(
            VentanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaErrorLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(51, 51, 51))
            .addGroup(VentanaErrorLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(AceptarErrorBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaErrorLayout.setVerticalGroup(
            VentanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaErrorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(AceptarErrorBtn)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        GeneroPadreBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno" }));
        GeneroPadreBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroPadreBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Genero Padre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(GeneroPadreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(VentanaError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(AceptarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelarBtn)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GeneroPadreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(VentanaError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarBtn)
                    .addComponent(AceptarBtn))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre: ");

        textoIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIngresadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(textoIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelarBtnActionPerformed

    private void AceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBtnActionPerformed
        // TODO add your handling code here:
       GeneroController GenController = new GeneroController();
       String texto = textoIngresado.getText();
       String generoPadre = GeneroPadreBox.getSelectedItem().toString();
       Genero padre = new Genero();
       System.out.println(GeneroPadreBox.getName());

       List<String> listaGeneros = GenController.obtenerNombresGeneros();
        boolean generoExiste = false;
        
    if(GeneroPadreBox.getName() != "Ninguno"){
         padre = GenController.findGenero(generoPadre);
    }
       
    
        

    // Recorre la lista para verificar si ya existe el string
    for (String genero : listaGeneros) {
        if (genero.equals(texto)) {
            generoExiste = true;
            break; // Sale del bucle si encuentra el string
        }
    }

    // Si no existe, añade el string a la lista
    if (!generoExiste && GeneroPadreBox.getName() == "Ninguno") {
        GenController.registrarGenero2(texto);
        JOptionPane.showMessageDialog(this,"Genero creado exitosamente.","Éxito",JOptionPane.INFORMATION_MESSAGE);
    } else if (!generoExiste && GeneroPadreBox.getName() != "Ninguno") {
        GenController.registrarGenero(texto, padre);
        JOptionPane.showMessageDialog(this,"Genero creado exitosamente.","Éxito",JOptionPane.INFORMATION_MESSAGE);
    }else{
        JOptionPane.showMessageDialog(this,"Ocurrió un error: El genero ingresado ya existe","Error",JOptionPane.ERROR_MESSAGE);
    }

    
//      if (!generoExiste ) {
//        GenController.registrarGenero(texto, padre);
//        JOptionPane.showMessageDialog(this,"Genero creado exitosamente.","Éxito",JOptionPane.INFORMATION_MESSAGE);
//    } else {
//        JOptionPane.showMessageDialog(this,"Ocurrió un error: El genero ingresado ya existe","Error",JOptionPane.ERROR_MESSAGE);
//    }
       
        GeneroPadreBox.removeAllItems();
        GeneroPadreBox.addItem("Ninguno");
        
         List<String> nombresGenero = GenController.obtenerNombresGeneros();
            for (String nombreG : nombresGenero) {
                GeneroPadreBox.addItem(nombreG);
            }
        
        
    }//GEN-LAST:event_AceptarBtnActionPerformed

    private void textoIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoIngresadoActionPerformed

    private void AceptarErrorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarErrorBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarErrorBtnActionPerformed

    private void GeneroPadreBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroPadreBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroPadreBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBtn;
    private javax.swing.JButton AceptarErrorBtn;
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JComboBox<String> GeneroPadreBox;
    private javax.swing.JPanel VentanaError;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoIngresado;
    // End of variables declaration//GEN-END:variables
}
