/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import controllers.Fabrica;
import controllers.ICancionController;
import controllers.IPlaylistController;
import controllers.IUsuarioController;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
public class AltaTemaLista extends javax.swing.JInternalFrame {
    Fabrica fabrica = Fabrica.getInstance();
    ICancionController cancionController = fabrica.getICancionController();
    IPlaylistController controladorP = fabrica.getIPlaylistController();
    IUsuarioController controladorUsuario = fabrica.getIUsuarioController();
    /**
     * Creates new form ConsultaUsuario
     */
    public AltaTemaLista() {
        initComponents();
        initComponents();
        PanelUsuario.setVisible(true);
        PanelPlaylist.setVisible(false);
        PanelTema.setVisible(false);
        PlaylistBoxP.setVisible(false);
         List<String> nombresClientes = controladorUsuario.obtenerNombresClientes();
            for (String nombreC : nombresClientes) {
                ClienteBox.addItem(nombreC);
            }
         List<String> nombresPlaylistD = controladorP.obtenerNombresPlaylistPorDefecto();
            for (String nombreP :  nombresPlaylistD) {
                PlaylistBoxD.addItem(nombreP);
            } 
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CheckPorDefecto = new javax.swing.JCheckBox();
        crearBtn = new javax.swing.JButton();
        PanelUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ClienteBox = new javax.swing.JComboBox<>();
        PanelPlaylist = new javax.swing.JPanel();
        PlaylistBoxD = new javax.swing.JComboBox<>();
        PlaylistBoxP = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        PanelTema = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        temasBox = new javax.swing.JComboBox<>();

        jLabel2.setText("lista de reproduccion");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta Tema Lista");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(400, 400));

        CheckPorDefecto.setText("Por defecto?");
        CheckPorDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPorDefectoActionPerformed(evt);
            }
        });

        crearBtn.setText("Crear");
        crearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearBtnMouseClicked(evt);
            }
        });
        crearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("usuario");

        ClienteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Usuario" }));
        ClienteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(ClienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ClienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelPlaylist.setToolTipText("");

        PlaylistBoxD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Playlist" }));
        PlaylistBoxD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlaylistBoxDMouseClicked(evt);
            }
        });
        PlaylistBoxD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaylistBoxDActionPerformed(evt);
            }
        });

        PlaylistBoxP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Playlist" }));
        PlaylistBoxP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlaylistBoxPMouseClicked(evt);
            }
        });
        PlaylistBoxP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaylistBoxPActionPerformed(evt);
            }
        });

        jLabel4.setText("lista de reproduccion");

        javax.swing.GroupLayout PanelPlaylistLayout = new javax.swing.GroupLayout(PanelPlaylist);
        PanelPlaylist.setLayout(PanelPlaylistLayout);
        PanelPlaylistLayout.setHorizontalGroup(
            PanelPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPlaylistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlaylistBoxD, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlaylistBoxP, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        PanelPlaylistLayout.setVerticalGroup(
            PanelPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaylistBoxP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(PlaylistBoxD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("nombre de tema");

        temasBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tema" }));

        javax.swing.GroupLayout PanelTemaLayout = new javax.swing.GroupLayout(PanelTema);
        PanelTema.setLayout(PanelTemaLayout);
        PanelTemaLayout.setHorizontalGroup(
            PanelTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(temasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        PanelTemaLayout.setVerticalGroup(
            PanelTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTemaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(PanelTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(temasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(CheckPorDefecto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(crearBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(CheckPorDefecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(crearBtn)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void recargarTemas(String Box) {
        temasBox.removeAllItems();
        temasBox.addItem("Seleccione Tema");
        List<String> nombresCancion = controladorP.obtenerNombresDeCancionesNoPresentesPlaylist(Box);
        for (String nombreC : nombresCancion) {
            temasBox.addItem(nombreC);
        }
    }
    private void CheckPorDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPorDefectoActionPerformed
        if (CheckPorDefecto.isSelected()) {
             PanelUsuario.setVisible(false);
             PlaylistBoxP.setVisible(false);
             PanelPlaylist.setVisible(true);
             PlaylistBoxD.setVisible(true);
             PanelTema.setVisible(false);
             
        } else {
             PlaylistBoxP.setVisible(true);
             PanelUsuario.setVisible(true);
             PlaylistBoxD.setVisible(false);
             PanelPlaylist.setVisible(false);
             PanelTema.setVisible(false);
        }
    }//GEN-LAST:event_CheckPorDefectoActionPerformed

    private void crearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearBtnActionPerformed

    private void PlaylistBoxDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaylistBoxDActionPerformed
        if (!"Seleccione Playlist".equals(PlaylistBoxD.getSelectedItem())) {
            PanelTema.setVisible(true);
            recargarTemas(PlaylistBoxD.getSelectedItem().toString());
        }else{
        PanelTema.setVisible(false);
        }
    }//GEN-LAST:event_PlaylistBoxDActionPerformed

    private void PlaylistBoxPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaylistBoxPActionPerformed
        if (!"Seleccione Playlist".equals(PlaylistBoxP.getSelectedItem())) {
            PanelTema.setVisible(true);
            recargarTemas(PlaylistBoxP.getSelectedItem().toString());
        }else{
        PanelTema.setVisible(false);
        }
    }//GEN-LAST:event_PlaylistBoxPActionPerformed

    private void ClienteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteBoxActionPerformed
       
        String selectedCliente = ClienteBox.getSelectedItem().toString();
        ActionListener[] listeners = PlaylistBoxP.getActionListeners();
        for (ActionListener listener : listeners) {
            PlaylistBoxP.removeActionListener(listener);
        }
        PlaylistBoxP.removeAllItems();
        PlaylistBoxP.addItem("Seleccione Playlist");
        List<String> nombresPlaylistP = controladorP.obtenerNombresPlaylistParticularCliente(selectedCliente);
     
        for (String nombreP : nombresPlaylistP) {
            PlaylistBoxP.addItem(nombreP);
        }

        for (ActionListener listener : listeners) {
            PlaylistBoxP.addActionListener(listener);
        }

        PlaylistBoxP.setVisible(true);
        PanelPlaylist.setVisible(true);
        PlaylistBoxD.setVisible(false);
        PanelTema.setVisible(false);
    }//GEN-LAST:event_ClienteBoxActionPerformed

    private void crearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseClicked
        try {
            
            if (CheckPorDefecto.isSelected()&((!"Seleccione Playlist".equals(PlaylistBoxD.getSelectedItem()))&(!"Seleccione Tema".equals(temasBox.getSelectedItem())))) {
                controladorP.crearRelacionPlaylistCancion(PlaylistBoxD.getSelectedItem().toString(), temasBox.getSelectedItem().toString());
                JOptionPane.showMessageDialog(this, "Alta de Cancion en Playlist creada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                recargarTemas(PlaylistBoxD.getSelectedItem().toString());
            } else if(!CheckPorDefecto.isSelected()&((!"Seleccione Usuario".equals(ClienteBox.getSelectedItem()))&(!"Seleccione Playlist".equals(PlaylistBoxP.getSelectedItem()))&(!"Seleccione Tema".equals(temasBox.getSelectedItem())))) {
                controladorP.crearRelacionPlaylistCancion(PlaylistBoxP.getSelectedItem().toString(), temasBox.getSelectedItem().toString());
                JOptionPane.showMessageDialog(this, "Alta de Cancion en Playlist creada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                recargarTemas(PlaylistBoxP.getSelectedItem().toString());
            }
            else{
                JOptionPane.showMessageDialog(this, "Porfavor complete los campos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_crearBtnMouseClicked

    private void PlaylistBoxPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaylistBoxPMouseClicked
       
    }//GEN-LAST:event_PlaylistBoxPMouseClicked

    private void PlaylistBoxDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaylistBoxDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaylistBoxDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckPorDefecto;
    private javax.swing.JComboBox<String> ClienteBox;
    private javax.swing.JPanel PanelPlaylist;
    private javax.swing.JPanel PanelTema;
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JComboBox<String> PlaylistBoxD;
    private javax.swing.JComboBox<String> PlaylistBoxP;
    private javax.swing.JButton crearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> temasBox;
    // End of variables declaration//GEN-END:variables
}
