/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import controllers.GeneroController;
import controllers.PlaylistController;
import controllers.UsuarioController;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;


public class AltaLista extends javax.swing.JInternalFrame {
        UsuarioController controladorUsuario = new UsuarioController();
        PlaylistController controladorPlaylist = new PlaylistController();
        GeneroController controladorGenero = new GeneroController();
    /**
     * Creates new form ConsultaUsuario
     */
    public AltaLista() {
        initComponents();
        PanelParticular.setVisible(false);
        List<String> nombresClientes = controladorUsuario.obtenerNombresClientes();
            for (String nombreC : nombresClientes) {
                ClienteBox.addItem(nombreC);
            }
        List<String> nombresGenero = controladorGenero.obtenerNombresGeneros();
            for (String nombreG : nombresGenero) {
                GeneroBox.addItem(nombreG);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoLista = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreLista = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFile = new javax.swing.JTextField();
        btnFile = new javax.swing.JButton();
        PanelParticular = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ClienteBox = new javax.swing.JComboBox<>();
        PanelPorDefecto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        GeneroBox = new javax.swing.JComboBox<>();
        crearBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta Lista");
        setPreferredSize(new java.awt.Dimension(800, 600));

        TipoLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Defecto", "Particular" }));
        TipoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoListaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Lista");

        jLabel2.setText("Nombre de lista de reproduccion");

        NombreLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreListaActionPerformed(evt);
            }
        });

        jLabel6.setText("Elige foto de lista:");

        txtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileActionPerformed(evt);
            }
        });

        btnFile.setText("Select");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliente");

        ClienteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione cliente" }));
        ClienteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelParticularLayout = new javax.swing.GroupLayout(PanelParticular);
        PanelParticular.setLayout(PanelParticularLayout);
        PanelParticularLayout.setHorizontalGroup(
            PanelParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelParticularLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(ClienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        PanelParticularLayout.setVerticalGroup(
            PanelParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(ClienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("Genero");

        GeneroBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione genero" }));
        GeneroBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPorDefectoLayout = new javax.swing.GroupLayout(PanelPorDefecto);
        PanelPorDefecto.setLayout(PanelPorDefectoLayout);
        PanelPorDefectoLayout.setHorizontalGroup(
            PanelPorDefectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorDefectoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(GeneroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        PanelPorDefectoLayout.setVerticalGroup(
            PanelPorDefectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPorDefectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(GeneroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        crearBtn.setText("Crear");
        crearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearBtnMouseClicked(evt);
            }
        });
        crearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreLista, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnFile)
                        .addGap(481, 481, 481))))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(crearBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelParticular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelPorDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelPorDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelParticular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(crearBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoListaActionPerformed
        
        //ClienteBox.removeAllItems();
        //GeneroBox.removeAllItems();
        
        if ("Por Defecto".equals(TipoLista.getSelectedItem())) {
            PanelParticular.setVisible(false);
            PanelPorDefecto.setVisible(true);

        } else {
            PanelPorDefecto.setVisible(false);
            PanelParticular.setVisible(true);

        }

    }//GEN-LAST:event_TipoListaActionPerformed

    private void NombreListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreListaActionPerformed

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc= new JFileChooser();
        //filtrar a solo imagenes jpg
        FileFilter filter = new FileNameExtensionFilter("Imagen", "jpg", "png");
        fc.setFileFilter(filter);

        fc.showOpenDialog(fc);
        File imgfile = fc.getSelectedFile();
        String filepath=imgfile.getAbsolutePath();
        txtFile.setText(filepath);
    }//GEN-LAST:event_btnFileActionPerformed

    private void txtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileActionPerformed

    private void crearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearBtnActionPerformed

    private void ClienteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteBoxActionPerformed
         List<String> nombresClientes = controladorUsuario.obtenerNombresClientes();
            for (String nombreC : nombresClientes) {
                ClienteBox.addItem(nombreC);
               // System.out.println(nombreC);
            }
    }//GEN-LAST:event_ClienteBoxActionPerformed

    private void crearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseClicked
        try {
            if ("Por Defecto".equals(TipoLista.getSelectedItem())&(!NombreLista.getText().isEmpty() & !"Seleccione genero".equals(GeneroBox.getSelectedItem().toString())& !txtFile.getText().isEmpty())) {
                controladorPlaylist.crearPlaylistPorDefecto(NombreLista.getText(),GeneroBox.getSelectedItem().toString(),txtFile.getText());
                JOptionPane.showMessageDialog(this,"Playlist por defecto creada exitosamente.","Éxito",JOptionPane.INFORMATION_MESSAGE);
            } else if ("Particular".equals(TipoLista.getSelectedItem())&(!NombreLista.getText().isEmpty() & !"Seleccione cliente".equals(ClienteBox.getSelectedItem().toString())& !txtFile.getText().isEmpty())) {
                controladorPlaylist.crearPlaylistParticular(NombreLista.getText(),txtFile.getText(),ClienteBox.getSelectedItem().toString());
                JOptionPane.showMessageDialog(this,"Playlist particular creada exitosamente.","Éxito",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Porfavor complete los campos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Ocurrió un error: " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_crearBtnMouseClicked

    private void GeneroBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroBoxActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClienteBox;
    private javax.swing.JComboBox<String> GeneroBox;
    private javax.swing.JTextField NombreLista;
    private javax.swing.JPanel PanelParticular;
    private javax.swing.JPanel PanelPorDefecto;
    private javax.swing.JComboBox<String> TipoLista;
    private javax.swing.JButton btnFile;
    private javax.swing.JButton crearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFile;
    // End of variables declaration//GEN-END:variables
}
