/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import controllers.Fabrica;
import controllers.IAlbumController;
import controllers.ICancionController;
import controllers.IGeneroController;
import controllers.IUsuarioController;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Album;


/**
 *
 * @author lilia
 */
public class ConsultarAlbum extends javax.swing.JInternalFrame {
Fabrica fabrica = Fabrica.getInstance();
IGeneroController genController = fabrica.getIGeneroController();
IUsuarioController UController = fabrica.getIUsuarioController();
IAlbumController AController = fabrica.getIAlbumController();
ICancionController CController= fabrica.getICancionController();
DefaultTableModel sinNada = new DefaultTableModel();

    /**
     * Creates new form ConsultarAlbum
     */

    public ConsultarAlbum() {
        initComponents();
        ComboBoxArtista.setVisible(false);
        ComboBoxGenero.setVisible(false);
        TablaAlbum.setVisible(false);
        ArtistaL.setVisible(false);
        GeneroL.setVisible(false);
        
       
        
        List<String> nombresGenero = genController.obtenerNombresGeneros();
        for (String nombreG : nombresGenero) {
            ComboBoxGenero.addItem(nombreG);
        }
         List<String> nombresArtistas = UController.obtenerNombresArtistas();
        for (String nombreA : nombresArtistas) {
            ComboBoxArtista.addItem(nombreA);
        }
        
          
    }
class NonEditableTableModel extends DefaultTableModel {

        public NonEditableTableModel(Object[][] data, Object[] columnNames) {
            super(data, columnNames);
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        DatosAlbum = new javax.swing.JTable();
        ComboBoxFiltro = new javax.swing.JComboBox<>();
        ComboBoxGenero = new javax.swing.JComboBox<>();
        ComboBoxArtista = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAlbum = new javax.swing.JTable();
        GeneroL = new javax.swing.JLabel();
        ArtistaL = new javax.swing.JLabel();

        jFrame1.setTitle("Consulta Album");
        jFrame1.setMinimumSize(new java.awt.Dimension(1000, 500));

        DatosAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DatosAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatosAlbumMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DatosAlbum);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        ComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtro", "Artista", "Genero" }));
        ComboBoxFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFiltroActionPerformed(evt);
            }
        });

        ComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        ComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGeneroActionPerformed(evt);
            }
        });

        ComboBoxArtista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        ComboBoxArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxArtistaActionPerformed(evt);
            }
        });

        TablaAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Albums"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAlbumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaAlbum);

        GeneroL.setText("Genero:");

        ArtistaL.setText("Artista:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GeneroL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ArtistaL)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GeneroL)
                            .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ArtistaL)
                            .addComponent(ComboBoxArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFiltroActionPerformed
        // TODO add your handling code here:
        if ("Artista".equals(ComboBoxFiltro.getSelectedItem())){
           TablaAlbum.setModel(sinNada);
           ComboBoxArtista.setVisible(true);
           ArtistaL.setVisible(true);
           GeneroL.setVisible(false);
           ComboBoxGenero.setVisible(false);
           
        }else if("Genero".equals(ComboBoxFiltro.getSelectedItem())){
            TablaAlbum.setModel(sinNada);
            ComboBoxGenero.setVisible(true);
            GeneroL.setVisible(true);
            ArtistaL.setVisible(false);
            ComboBoxArtista.setVisible(false);
            
        }else{
        TablaAlbum.setModel(sinNada);
           ComboBoxGenero.setVisible(false);
            GeneroL.setVisible(false);
            ArtistaL.setVisible(false);
            ComboBoxArtista.setVisible(false);
        }
    }//GEN-LAST:event_ComboBoxFiltroActionPerformed

    private void ComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    String generoSeleccionado = ComboBoxGenero.getSelectedItem().toString();
    String[] columnNames = {"ID","Álbum"};
    Object[][] data = AController.obtenerAlbumesPorGeneroObj(generoSeleccionado);
    
    NonEditableTableModel modelo= new NonEditableTableModel(data,columnNames);
    TablaAlbum.setModel(modelo);
        
    
    TablaAlbum.setVisible(true);  
        
    }//GEN-LAST:event_ComboBoxGeneroActionPerformed

    private void ComboBoxArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxArtistaActionPerformed
        // TODO add your handling code here:
    String artistaSeleccionado = ComboBoxArtista.getSelectedItem().toString();
    String[] columnNames = {"ID","Álbum"};
    Object[][] data = AController.obtenerAlbumArtistaObj(artistaSeleccionado);
    
     NonEditableTableModel modelo= new NonEditableTableModel(data,columnNames);
    TablaAlbum.setModel(modelo);
    TablaAlbum.setVisible(true);  // Mostrar la tabla
    }//GEN-LAST:event_ComboBoxArtistaActionPerformed

    private void TablaAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAlbumMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) { // Detectar clic simple
            int row = TablaAlbum.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                int id = (Integer) TablaAlbum.getValueAt(row, 0);
                Object[][] datos = AController.obtenerDatosAlbum(id);
                jFrameAlbum jframe = new jFrameAlbum(datos); 
                jframe.setVisible(true);
                
                /*DatosAlbum.setRowHeight(140);
                DatosAlbum.setFont(new Font("Arial", Font.PLAIN, 16));
                DatosAlbum.setShowGrid(true);
                String id = (String) TablaAlbum.getValueAt(row, 0); 
                jFrame1.setVisible(true);
                Object[][] datos = AController.obtenerDatosAlbum(id);
                String[] columnNames = {"IMAGEN","ID" , "NOMBRE", "AÑO" ,"ARTISTA", "GENEROS", "CANCIONES"};
                NonEditableTableModel tableModel = new NonEditableTableModel(datos, columnNames);
                DatosAlbum.setModel(tableModel);
                DatosAlbum.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer());
                */
            }
        }
    }//GEN-LAST:event_TablaAlbumMouseClicked

    private void DatosAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatosAlbumMouseClicked
       /*
        if (evt.getClickCount() == 2) { // Detectar clic simple
            int row = DatosAlbum.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                int id = (int) DatosAlbum.getValueAt(row, 1); // Cambia 1 al índice de la columna deseada
                Object[][] datos = CController.obtenerDatosCancion(id);
                jFrameCanciones jFrameC = new jFrameCanciones(datos);
                jFrameC.setVisible(true);
                
            }
        }*/
    }//GEN-LAST:event_DatosAlbumMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArtistaL;
    private javax.swing.JComboBox<String> ComboBoxArtista;
    private javax.swing.JComboBox<String> ComboBoxFiltro;
    private javax.swing.JComboBox<String> ComboBoxGenero;
    private javax.swing.JTable DatosAlbum;
    private javax.swing.JLabel GeneroL;
    private javax.swing.JTable TablaAlbum;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
