/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import controllers.GeneroController;
import controllers.PlaylistController;
import controllers.UsuarioController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import views.ImageRenderer;

public class ConsultarPlaylist extends javax.swing.JInternalFrame {
    PlaylistController controladorP = new PlaylistController();
    UsuarioController controladorUsuario = new UsuarioController();
    GeneroController controladorGenero = new GeneroController();
    
    /**
     * Creates new form ConsultaUsuario
     */
    public ConsultarPlaylist() {
        initComponents();
        DatosGenero.setVisible(false);
        DatosCliente.setVisible(false);

        List<String> nombresClientes = controladorUsuario.obtenerNombresClientes();
        for (String nombreC : nombresClientes) {
            DatosCliente.addItem(nombreC);
        }
        List<String> nombresGenero = controladorGenero.obtenerNombresGeneros();
        for (String nombreG : nombresGenero) {
            DatosGenero.addItem(nombreG);
        }
    }

    class NonEditableTableModel extends DefaultTableModel {

        public NonEditableTableModel(Object[][] data, Object[] columnNames) {
            super(data, columnNames);
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        canciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPlaylist = new javax.swing.JTable();
        GeneroCliente = new javax.swing.JComboBox<>();
        DatosGenero = new javax.swing.JComboBox<>();
        DatosCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        jFrame2.setTitle("Canciones");
        jFrame2.setLocation(new java.awt.Point(500, 500));
        jFrame2.setMinimumSize(new java.awt.Dimension(300, 300));
        jFrame2.setSize(new java.awt.Dimension(300, 300));

        canciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(canciones);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Playlist");
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(637, 400));

        ListaPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "RUTA IMAGEN", "TIPO", "PRIVADA", "GENERO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaPlaylistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaPlaylist);

        GeneroCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione filtro", "Todas", "Genero", "Cliente" }));
        GeneroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroCliente(evt);
            }
        });

        DatosGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Genero" }));
        DatosGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosGeneroActionPerformed(evt);
            }
        });

        DatosCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Cliente" }));
        DatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("FILTRO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(598, 598, 598)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(DatosGenero, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DatosCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GeneroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GeneroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DatosGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneroCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroCliente
      
        if ("Todas".equals(GeneroCliente.getSelectedItem())) {
            DatosGenero.setVisible(false);
            DatosCliente.setVisible(false);
            Object[][] datos = controladorP.obtenerPlaylistLista();
            String[] columnNames = {"ID", "NOMBRE", "RUTAIMAGEN", "DTYPE","PRIVADA","GENERO"};
            NonEditableTableModel tableModel = new NonEditableTableModel(datos, columnNames);
            ListaPlaylist.setModel(tableModel);
            ListaPlaylist.getColumnModel().getColumn(2).setCellRenderer(new ImageRenderer());
         
        } 
        else if ("Genero".equals(GeneroCliente.getSelectedItem())) {
            DatosGenero.setVisible(true);
            DatosCliente.setVisible(false);

        } else if("Cliente".equals(GeneroCliente.getSelectedItem())){
            DatosGenero.setVisible(false);
            DatosCliente.setVisible(true);

        }else{
            DatosGenero.setVisible(false);
            DatosCliente.setVisible(false);
        }
        
        
    }//GEN-LAST:event_GeneroCliente

    private void DatosGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosGeneroActionPerformed
        ListaPlaylist.setVisible(true);
       if ("Genero".equals(GeneroCliente.getSelectedItem())) {
            Object[][] datos = controladorP.obtenerDatosPlaylistGenero(DatosGenero.getSelectedItem().toString());
            String[] columnNames = {"ID", "NOMBRE", "RUTAIMAGEN", "DTYPE", "GENERO"};
            NonEditableTableModel tableModel = new NonEditableTableModel(datos, columnNames);
            ListaPlaylist.setModel(tableModel);
            ListaPlaylist.getColumnModel().getColumn(2).setCellRenderer(new ImageRenderer());
        
        }
 
    }//GEN-LAST:event_DatosGeneroActionPerformed

    private void DatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosClienteActionPerformed

        if ("Cliente".equals(GeneroCliente.getSelectedItem())){
            Object[][] datos = controladorP.obtenerDatosPlaylistCliente(DatosCliente.getSelectedItem().toString());
            String[] columnNames = {"ID", "NOMBRE", "RUTAIMAGEN", "DTYPE", "PRIVADA"};
            NonEditableTableModel tableModel = new NonEditableTableModel(datos, columnNames);
            ListaPlaylist.setModel(tableModel);
            ListaPlaylist.getColumnModel().getColumn(2).setCellRenderer(new ImageRenderer());
            
        }
    }//GEN-LAST:event_DatosClienteActionPerformed

    private void ListaPlaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaPlaylistMouseClicked
        if (evt.getClickCount() == 2) { // Detectar clic simple
            int row = ListaPlaylist.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                // Obtener el valor de una columna específica, por ejemplo, la columna con índice 1
                int id = (int) ListaPlaylist.getValueAt(row, 0); // Cambia 1 al índice de la columna deseada
                jFrame2.setVisible(true);
                Object[][] datos = controladorP.obtenerDatosPlaylist(id);
                String[] columnNames = {"ID", "NOMBRE", "RUTAIMAGEN","RUTA MP3","DURACION", "GENERO"};
                NonEditableTableModel tableModel = new NonEditableTableModel(datos, columnNames);
                canciones.setModel(tableModel);
                canciones.getColumnModel().getColumn(2).setCellRenderer(new ImageRenderer());
            }
        }
    }//GEN-LAST:event_ListaPlaylistMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DatosCliente;
    private javax.swing.JComboBox<String> DatosGenero;
    private javax.swing.JComboBox<String> GeneroCliente;
    private javax.swing.JTable ListaPlaylist;
    private javax.swing.JTable canciones;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
