/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import controllers.Fabrica;
import controllers.IUsuarioController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dylan
 */

public class ConsultarArtista extends javax.swing.JInternalFrame {
 Fabrica fabrica = Fabrica.getInstance();
 IUsuarioController usrController = fabrica.getIUsuarioController();
 class NonEditableTableModel extends DefaultTableModel {

        public NonEditableTableModel(Object[][] data, Object[] columnNames) {
            super(data, columnNames);
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }   
 /**
     * Creates new form ConsultaUsuario
     */
    public ConsultarArtista() {
        initComponents();
    
        Object[][] datos = usrController.obtenerDatosArtistas();
        String[] columnNames = {"NOMBRE", "NICK"};
        NonEditableTableModel tableModel = new NonEditableTableModel(datos, columnNames);
        tablaArtistas.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArtistas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        tablaArtistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Artistas"
            }
        ));
        tablaArtistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArtistasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaArtistas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaArtistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArtistasMouseClicked
        if (evt.getClickCount() == 2) { // Detectar clic doble
            int row = tablaArtistas.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                try {
                    // Obtener el valor de una columna específica
                    String id = (String) tablaArtistas.getValueAt(row, 1);
                    
                    Object[][] datos = usrController.obtenerDatosArtista(id);
                    jFrameUsuarios jframeu = new jFrameUsuarios(datos);
                    jframeu.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ConsultarArtista.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        }
    }//GEN-LAST:event_tablaArtistasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaArtistas;
    // End of variables declaration//GEN-END:variables
}
